#!/usr/bin/env python3
"""Build the item/tag id snapshot used by validate_recipes.py.

The snapshot lists every item id vanilla 1.21.1 knows about, so the recipe
validator can tell a real id from a typo. It is generated from the client jar
rather than typed by hand:

* ``assets/minecraft/models/item/<name>.json`` - one file per item model
* ``assets/minecraft/blockstates/<name>.json`` - one file per block, and every
  block has a matching block item
* every ``result.id`` in ``data/minecraft/recipe/*.json``
* ``data/minecraft/tags/item/<name>.json`` - the item tags

Usage::

    python tools/make_item_id_snapshot.py <client-jar> -o tools/item_ids.json

Long Minecraft versions change the registry, so regenerate this whenever
``minecraft_version`` in gradle.properties changes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile

ITEM_MODEL_RE = re.compile(r"^assets/minecraft/models/item/(.+)\.json$")
BLOCKSTATE_RE = re.compile(r"^assets/minecraft/blockstates/(.+)\.json$")
RECIPE_RE = re.compile(r"^data/minecraft/recipe/.+\.json$")
TAG_RE = re.compile(r"^data/minecraft/tags/item/(.+)\.json$")


def collect(jar_path: str) -> tuple[set[str], set[str]]:
    items: set[str] = set()
    tags: set[str] = set()

    with zipfile.ZipFile(jar_path) as jar:
        names = jar.namelist()

        for name in names:
            match = ITEM_MODEL_RE.match(name) or BLOCKSTATE_RE.match(name)
            if match:
                items.add("minecraft:" + match.group(1))

        for name in names:
            match = TAG_RE.match(name)
            if match:
                tags.add("minecraft:" + match.group(1))

        # Recipe outputs widen the set: a few items have no model of their own.
        for name in names:
            if not RECIPE_RE.match(name):
                continue
            try:
                recipe = json.loads(jar.read(name).decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue
            result = recipe.get("result")
            if isinstance(result, str):
                items.add(result)
            elif isinstance(result, dict) and isinstance(result.get("id"), str):
                items.add(result["id"])

    return items, tags


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the vanilla item/tag id snapshot.")
    parser.add_argument("client_jar", help="Minecraft client jar (or a merged/version jar with vanilla assets)")
    parser.add_argument("-o", "--output", required=True, help="where to write the snapshot JSON")
    args = parser.parse_args()

    try:
        items, tags = collect(args.client_jar)
    except (OSError, zipfile.BadZipFile) as exc:
        print(f"cannot read {args.client_jar}: {exc}", file=sys.stderr)
        return 1

    if not items:
        print(f"no item ids found in {args.client_jar}; is this really a client jar?", file=sys.stderr)
        return 1

    payload = {
        "_comment": (
            "Generated by tools/make_item_id_snapshot.py from the Minecraft client jar. "
            "Contains every vanilla item id and item tag id, so recipe validation can "
            "detect unknown ids. Regenerate when minecraft_version changes."
        ),
        "items": sorted(items),
        "tags": sorted(tags),
    }
    with open(args.output, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=1)
        handle.write("\n")

    print(f"wrote {args.output}: {len(items)} item ids, {len(tags)} item tags")
    return 0


if __name__ == "__main__":
    sys.exit(main())
