#!/usr/bin/env python3
"""Validate ICU recipe files against the Minecraft 1.21.1 recipe format.

Why this exists
---------------
Version 0.2.0 shipped a bandage recipe whose ``ingredients`` were bare strings::

    "ingredients": ["minecraft:paper", "minecraft:string"]

1.21.1 requires each entry to be an object (or an array of alternatives), so the
recipe manager rejected the file at load time with::

    Parsing error loading recipe icu:bandage
    JsonParseException: Not a json array: "minecraft:paper"

Nothing caught it: the file existed, the JSON was valid, the item ids were real,
and the jar packaged cleanly. The recipe simply never appeared in game, which
made the bandage uncraftable and bleeding untreatable. A compile step cannot see
this; parsing the file the way the game parses it can.

This script therefore reproduces the two checks the game performs:

1. **Decode** - the file must parse as a recipe of a known type, with the shape
   that type requires.
2. **Resolve** - every item and tag id referenced must exist in the vanilla
   1.21.1 data. Ids introduced by this mod (namespace ``icu``) are accepted;
   they are checked for shape only, because the script has no registry to
   consult for them.

Usage::

    python tools/validate_recipes.py <recipes-dir> --ids <item-ids.json>

``item-ids.json`` is generated by ``tools/make_item_id_snapshot.py``.
Exit code is 0 when everything passes, 1 otherwise.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

# Recipe types whose body this script understands.
SHAPELESS = "minecraft:crafting_shapeless"
SHAPED = "minecraft:crafting_shaped"
SMELTING = {
    "minecraft:smelting",
    "minecraft:blasting",
    "minecraft:smoking",
    "minecraft:campfire_cooking",
}
STONECUTTING = "minecraft:stonecutting"
SMITHING = "minecraft:smithing_transform"
CRAFTING_SPECIAL = {
    "minecraft:crafting_special_armordye",
    "minecraft:crafting_special_bannerduplicate",
    "minecraft:crafting_special_bookcloning",
    "minecraft:crafting_special_firework_rocket",
    "minecraft:crafting_special_firework_star",
    "minecraft:crafting_special_firework_star_fade",
    "minecraft:crafting_special_mapcloning",
    "minecraft:crafting_special_mapextending",
    "minecraft:crafting_special_repairitem",
    "minecraft:crafting_special_shielddecoration",
    "minecraft:crafting_special_shulkerboxcoloring",
    "minecraft:crafting_special_suspiciousstew",
    "minecraft:crafting_special_tippedarrow",
    "minecraft:crafting_special_banneraddpattern",
}
KNOWN_TYPES = {SHAPELESS, SHAPED, STONECUTTING, SMITHING} | SMELTING | CRAFTING_SPECIAL

ID_RE = re.compile(r"^[a-z0-9_.-]+:[a-z0-9_./-]+$")

# Ingredients that are allowed to be an empty list or an empty object: the game
# uses these as "no ingredient" placeholders in a few synthetic recipes.
ALLOW_EMPTY = False


class Problems:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, where: str, message: str) -> None:
        self.errors.append(f"{where}: {message}")

    def warn(self, where: str, message: str) -> None:
        self.warnings.append(f"{where}: {message}")


def check_item_id(where: str, value: object, ids: set[str], problems: Problems) -> None:
    """An item id must be a namespaced string that really exists."""
    if not isinstance(value, str):
        problems.error(where, f"item id must be a string, got {type(value).__name__}: {value!r}")
        return
    if not ID_RE.match(value):
        problems.error(where, f"malformed item id {value!r} (expected namespace:path)")
        return
    namespace = value.split(":", 1)[0]
    if namespace == "icu":
        return  # this mod's own items; no registry available here
    if ids and value not in ids:
        # The game's recipe manager rejects unknown item ids outright, and the
        # snapshot covers every vanilla item (item models + blockstates + recipe
        # outputs), so an id that is not there is a real typo, not a gap.
        problems.error(where, f"unknown item id {value!r}; not in the vanilla 1.21.1 snapshot")


def check_tag_id(where: str, value: object, tags: set[str], problems: Problems) -> None:
    if not isinstance(value, str):
        problems.error(where, f"tag id must be a string, got {type(value).__name__}: {value!r}")
        return
    if not ID_RE.match(value):
        problems.error(where, f"malformed tag id {value!r} (expected namespace:path)")
        return
    namespace = value.split(":", 1)[0]
    if namespace == "icu":
        return
    if tags and value not in tags:
        problems.error(where, f"unknown tag id {value!r}; not in the vanilla 1.21.1 snapshot")


def check_ingredient(where: str, value: object, ids: set[str], tags: set[str], problems: Problems) -> None:
    """One ingredient, in any of the three shapes 1.21.1 accepts.

    ``"minecraft:paper"``         - bare string, allowed here
    ``["minecraft:paper", ...]``  - alternatives
    ``{"item": "..."}`` / ``{"tag": "..."}``
    """
    if isinstance(value, str):
        # A bare string is REJECTED by the 1.21.1 Ingredient codec. The game
        # tries to parse it as an array, then as an object, and fails both:
        #   "Not a json array: ...; Not a JSON object: ..."
        # This is exactly what broke the 0.2.0 bandage recipe, so it must be
        # an error, not a warning.
        problems.error(
            where,
            f"bare string ingredient {value!r} is not valid in 1.21.1; use {{\"item\": {value!r}}}",
        )
        return
    if isinstance(value, list):
        if not value and not ALLOW_EMPTY:
            problems.error(where, "empty alternatives list")
            return
        for i, alt in enumerate(value):
            check_ingredient(f"{where}[{i}]", alt, ids, tags, problems)
        return
    if isinstance(value, dict):
        keys = set(value)
        if keys == {"item"}:
            check_item_id(where, value["item"], ids, problems)
        elif keys == {"tag"}:
            check_tag_id(where, value["tag"], tags, problems)
        else:
            problems.error(
                where,
                f"ingredient object must be exactly {{\"item\": ...}} or {{\"tag\": ...}}, got keys {sorted(keys)}",
            )
        return
    problems.error(where, f"ingredient must be a string, list or object, got {type(value).__name__}: {value!r}")


def check_ingredients_list(where: str, value: object, ids: set[str], tags: set[str], problems: Problems) -> None:
    if not isinstance(value, list):
        problems.error(where, f"\"ingredients\" must be a JSON array, got {type(value).__name__}: {value!r}")
        return
    if not value:
        problems.error(where, "shapeless recipe has no ingredients")
        return
    for i, ing in enumerate(value):
        check_ingredient(f"{where}.ingredients[{i}]", ing, ids, tags, problems)


def check_result(where: str, value: object, ids: set[str], problems: Problems) -> None:
    if isinstance(value, str):
        problems.warn(where, f"legacy string result {value!r}; 1.21.1 uses {{\"id\": ...}}")
        check_item_id(where, value, ids, problems)
        return
    if not isinstance(value, dict):
        problems.error(where, f"\"result\" must be an object, got {type(value).__name__}: {value!r}")
        return
    if "id" not in value:
        problems.error(where, f"\"result\" has no \"id\" key (keys: {sorted(value)})")
        return
    check_item_id(f"{where}.result.id", value["id"], ids, problems)
    count = value.get("count")
    if count is not None and (not isinstance(count, int) or isinstance(count, bool) or count < 1):
        problems.error(where, f"\"result.count\" must be a positive integer, got {count!r}")


def check_recipe(path: str, display: str, ids: set[str], tags: set[str], problems: Problems) -> None:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            raw = handle.read()
    except OSError as exc:
        problems.error(display, f"cannot read file: {exc}")
        return
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        problems.error(display, f"invalid JSON: {exc}")
        return
    if not isinstance(data, dict):
        problems.error(display, f"recipe must be a JSON object, got {type(data).__name__}")
        return

    recipe_type = data.get("type")
    if recipe_type is None:
        problems.error(display, "missing \"type\"")
        return
    if not isinstance(recipe_type, str):
        problems.error(display, f"\"type\" must be a string, got {type(recipe_type).__name__}")
        return
    if recipe_type not in KNOWN_TYPES:
        problems.error(display, f"unknown recipe type {recipe_type!r}")
        return

    if recipe_type == SHAPELESS:
        check_ingredients_list(display, data.get("ingredients"), ids, tags, problems)
        check_result(display, data.get("result"), ids, problems)
    elif recipe_type == SHAPED:
        pattern = data.get("pattern")
        if not isinstance(pattern, list) or not pattern or not all(isinstance(r, str) for r in pattern):
            problems.error(display, "\"pattern\" must be a non-empty array of strings")
        else:
            width = len(pattern[0])
            if any(len(r) != width for r in pattern):
                problems.error(display, "\"pattern\" rows must all be the same length")
            if len(pattern) > 3 or width > 3:
                problems.error(display, f"\"pattern\" is {len(pattern)}x{width}, larger than the 3x3 grid")
        key = data.get("key")
        if not isinstance(key, dict):
            problems.error(display, "\"key\" must be an object")
        else:
            if pattern:
                used = {c for row in pattern for c in row if c != " "}
                for symbol in sorted(used):
                    if symbol not in key:
                        problems.error(display, f"pattern uses symbol {symbol!r} that \"key\" does not define")
                for symbol in sorted(key):
                    if symbol not in used:
                        problems.warn(display, f"\"key\" defines unused symbol {symbol!r}")
            for symbol, ing in key.items():
                check_ingredient(f"{display}.key[{symbol!r}]", ing, ids, tags, problems)
        check_result(display, data.get("result"), ids, problems)
    elif recipe_type in SMELTING:
        check_ingredient(display + ".ingredient", data.get("ingredient"), ids, tags, problems)
        if "result" not in data:
            problems.error(display, "missing \"result\"")
        else:
            check_result(display, data.get("result"), ids, problems)
        if not isinstance(data.get("experience"), (int, float)) or isinstance(data.get("experience"), bool):
            problems.error(display, f"\"experience\" must be a number, got {data.get('experience')!r}")
        if not isinstance(data.get("cookingtime"), int) or isinstance(data.get("cookingtime"), bool):
            problems.error(display, f"\"cookingtime\" must be an integer, got {data.get('cookingtime')!r}")
    elif recipe_type == STONECUTTING:
        check_ingredient(display + ".ingredient", data.get("ingredient"), ids, tags, problems)
        check_result(display, data.get("result"), ids, problems)
        if not isinstance(data.get("count"), int) or isinstance(data.get("count"), bool):
            problems.error(display, f"\"count\" must be an integer, got {data.get('count')!r}")
    elif recipe_type == SMITHING:
        for field in ("template", "base", "addition"):
            if field not in data:
                problems.error(display, f"missing \"{field}\"")
            else:
                check_ingredient(f"{display}.{field}", data.get(field), ids, tags, problems)
        check_result(display, data.get("result"), ids, problems)


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate ICU recipe files for Minecraft 1.21.1.")
    parser.add_argument("recipes_dir", help="directory containing recipe JSON files (searched recursively)")
    parser.add_argument("--ids", help="item id snapshot JSON from make_item_id_snapshot.py")
    parser.add_argument(
        "--strict-warnings",
        action="store_true",
        help="treat warnings (unknown ids, bare string ingredients) as failures",
    )
    args = parser.parse_args()

    ids: set[str] = set()
    tags: set[str] = set()
    if args.ids:
        try:
            with open(args.ids, "r", encoding="utf-8") as handle:
                snapshot = json.load(handle)
            ids = set(snapshot.get("items", []))
            tags = set(snapshot.get("tags", []))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"cannot read id snapshot {args.ids}: {exc}", file=sys.stderr)
            return 1
    else:
        print("warning: no --ids snapshot given, item ids will not be checked", file=sys.stderr)

    if not os.path.isdir(args.recipes_dir):
        print(f"recipes directory not found: {args.recipes_dir}", file=sys.stderr)
        return 1

    files: list[str] = []
    for root, _dirs, names in os.walk(args.recipes_dir):
        for name in sorted(names):
            if name.endswith(".json"):
                files.append(os.path.join(root, name))
    files.sort()

    if not files:
        print(f"no recipe files found under {args.recipes_dir}", file=sys.stderr)
        return 1

    problems = Problems()
    for path in files:
        display = os.path.relpath(path).replace(os.sep, "/")
        check_recipe(path, display, ids, tags, problems)

    for warning in problems.warnings:
        print(f"warning: {warning}")
    for error in problems.errors:
        print(f"error: {error}")

    checked = f"{len(files)} recipe file(s)"
    if problems.errors:
        print(f"\nFAILED: {len(problems.errors)} problem(s) in {checked}")
        return 1
    if problems.warnings and args.strict_warnings:
        print(f"\nFAILED: {len(problems.warnings)} warning(s) in {checked} (--strict-warnings)")
        return 1
    if problems.warnings:
        print(f"\nok: {checked}, {len(problems.warnings)} warning(s)")
    else:
        print(f"\nok: {checked}, all valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
